### ISSUE TITLE
Assembly reference missing and fixes

### ISSUE THREAD

**Issue by megatran** [bryceikeda/HololensBaseProject#1]
Hello, thanks for providing the base sample project that saves everyone a lot of time.

I encountered several missing assembly references issues during the build step that I think are potentially caused by .gitignore.

For example, in the `Assets/Scripts` folder, I created a Assembly Definition asset file with the following references

![image](https://user-images.githubusercontent.com/10265967/182521300-a1f92fde-38e1-4c18-805b-e623c5188abd.png)

This resolves most of the missing references during build, however, there's one lingering

```
Assets\Scripts\TfTree\TransformTreeNode.cs(4,22): error CS0234: The type or namespace name 'UrdfImporter' does not exist in the namespace 'Unity.Robotics' (are you missing an assembly reference?)

``` 

As can be seen in the screenshot above, I did import `Unity.Robotics.URDFImporter`, but Unity Build still can't find it. One temporary solution is to completely remove reference of 
`using Unity.Robotics.UrdfImporter;` from the `TransformTreeNode.cs` script. Then we can use `GetComponent(string)` to get the Urdf Link to bypass the TryGetComponent by type.

```
                // If game object has a URDFLink attached, it's a link in the transform tree
                var urdfLink = childGO.GetComponent("UrdfLink");
                if (urdfLink != null)
                {
                    var childNode = new TransformTreeNode(childGO);
                    tfNode.Children.Add(childNode);
                }
```

Though, I'd  still be curious if you have a working assembly reference file that you could share? Or is there anything setting you think could be missing?

Thanks!

**Comment by bryceikeda** [comment]
Hi @megatran. Thanks for bringing this up! I can't remember why I had the TransformTreeNode.cs script so I removed it and fixed some other things. The project still has some warnings off of a fresh clone that I don't have time to fix right, but the project should work just fine now. Let me know if that's not the case.
